# Generated by Django 4.0.1 on 2022-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('creatAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('favourited', models.BooleanField()),
                ('favouriteCount', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
        ),
    ]
