# Generated by Django 4.0.1 on 2022-01-20 13:50

import django.core.validators
from django.db import migrations, models
import main.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_address_student_email_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0), main.validators.validate_even_number]),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.EmailValidator(message='Please check your email again')]),
        ),
    ]
